### ISSUE TITLE
Update M365DSC Composite Resources used in whitepaper "Managing Microsoft 365 in true DevOps style with Microsoft365DSC and Azure DevOps"

### ISSUE THREAD

**Issue by thixepp** [ykuijs/M365DSC.CompositeResources#2]
Dear Yorick,

First of all, thanks a lot for all your work.

I've deployed the solution described in the whitepaper (great doc, many thanks) based on the scripts provided for version v1.22.1019.1 (https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/M365Automation.zip). 

I'd now like to be able to update the M365DSC module, and to do so I also need to update the composite resources. So I've downloaded your package (https://psg-prod-eastus.azureedge.net/packages/m365dsc.compositeresources.1.24.515.200.nupkg) for version 1.24.515.200. 

What is the best practice for updating existing scripts in my DevOps environment? Should I simply replace the files included in DscResources? What happens to the M365Configuration.ps1 script? Should I extract the current configuration from my tenant and use the result as a base?

I'd like to have a clear procedure for doing this in the best possible way once it's used in production (I'm currently in the testing phase).

Many thanks for your help.
Best regards
Thierry

**Comment by ykuijs** [comment]
Hi @jesthepp, 

Good to hear the whitepaper is helping out! Mission accomplished 😉 

The M365DSC.CompositeResources module has been created as part of an update of the whitepaper I am working on. This new version of the whitepaper will be another leap forward and will provide a whole code framework which you can use to manage your M365 tenants using Microsoft365DSC. It contains a lot improvements compare to the scripts provided in the current version of the whitepaper.

I am currently in the process of updating the documentation and hope to publish this soon. If you share your contact details (for example via private message on X, my handle is @yorickkuijs) I will share a draft version once that is ready.

Regards,

Yorick

**Comment by thixepp** [comment]
Dear @ykuijs,

Thank you very much for your feedback.

I would be very grateful if you could share with me a first draft, even if it is not complete, so that I can start to understand the logic of this new framework, knowing that I need to be able to implement a first test version as soon as possible.

I'll send you my e-mail right away via a private message in X.
Thank you very much for your invaluable help!

Kind regards
Thierry
